### ISSUE TITLE
Morning session Peer to Peer Code Review (Week 4, Day 2)

### ISSUE THREAD

**Issue by AJ193** [AJ193/Portfolio-A#9]
You can check my code and give me some comments.

**Comment by katfogy** [comment]
-Please i recommend you add line-height to your paragraph tags, so that they will not be choke together.
-I suggest you add padding and margin to the contact section so that it will not be touching the end of the page.
-I recommend you use html Main semantic tag after the header semantic tag.
But i must confess you did a great job.

**Comment by Esmatullah12** [comment]
well done @AJ193  your code is nice 👏 but if you remove white lines and also use indentation your code will look more clean and good
